### PR TITLE
Chore/Apple

### PR DESCRIPTION
**Pull request by borut-t**
Updated response for Apple auth.

### CODE REVIEW

**Review by tonikocjan — COMMENTED** [review]
Can you explain the reasoning behind these changes?

**Comment by borut-t** [comment]
> Can you explain the reasoning behind these changes?

Email is required, expiration date is needed. There is no reason why one would continue with auth if this two parts are missing. Would you argue?

**Comment by tonikocjan** [comment]
> Email is required, expiration date is needed. There is no reason why one would continue with auth if this two parts are missing. Would you argue?

👍

**Review by tonikocjan — APPROVED** [review]
Lgtm.

**Pull request merged**
